// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fliijbcsxvyiuoptbcke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaWlqYmNzeHZ5aXVvcHRiY2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjExMTksImV4cCI6MjA2MTM5NzExOX0.8nehu0P3EVFgyNfuFpWP3QJ-MOrXM7urAYHWC2TEpdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);